version: '3.1'

services: 
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: admin
            POSTGRES_DB: bookstore
        ports:
            - "8001:5432"
        volumes:
            - database_data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: jesseverard21@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"

volumes:
    database_data:
        external: false